name: CI

on:

  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: setup node
        uses: actions/setup-node@v2-beta
        with:
          node-version: 14.18.3

      - name: Install Dependencies
        run: npm ci

      - uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: cypress-screenshots
          path: cypress/screenshots

      - name: Start Component Testing
        uses: cypress-io/github-action@v2
        with:
          install: false
          command: npx cypress run-ct

