name: CI

on:

  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  tests-components:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: setup node
        id: node
        uses: actions/setup-node@v2
        with:
          node-version: 14.18.3
          cache: 'npm'

      - name: Install Dependencies
        run: npm ci

      - name: Start Component Testing
        uses: cypress-io/github-action@v2
        with:
          install: false
          command: npx cypress run-ct

      - name: Record test failure
        uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: cypress-videos
          path: cypress/videos

  build:
    runs-on: ubuntu-latest
    needs: [tests-components]
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: setup node
        id: node
        uses: actions/setup-node@v2
        with:
          node-version: 14.18.3
          cache: 'npm'

      - name: Install Dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: save build
        uses: actions/upload-artifact@v2
        with:
          name: build
          path: dist/
